# Generated by Django 3.1.7 on 2021-08-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=2000)),
                ('rating', models.FloatField(default=0.0)),
                ('thumbnail_url', models.TextField()),
            ],
        ),
    ]
